name: Build C++
on:
  workflow_dispatch:
    inputs:
      whisper_cpp_repo:
        description: 'whisper.cpp repo link'
        required: true
        default: 'ggerganov/whisper.cpp'
      whisper_cpp_repo_ref:
        description: 'Tag, branch or commit'
        required: true
        default: 'v1.5.5'
jobs:
  build-android:
    name: Build for Android (arm64-v8a)
    runs-on: ubuntu-latest
    steps:          
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Android NDK
        run: |
          sdkmanager --install "build-tools;33.0.2"
          sdkmanager --install "cmake;3.22.1"
          sdkmanager --install "ndk;25.2.9519653"
          
      - name: Clone whisper.unity
        uses: actions/checkout@v3
        with:
          path: whisper-unity
          
      - name: Clone whisper.cpp
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.whisper_cpp_repo }}
          ref: ${{ github.event.inputs.whisper_cpp_repo_ref }}
          path: whisper-cpp
          
      - name: Run build script
        run: |
          cd whisper-unity
          sh build_cpp.sh ../whisper-cpp/ android $ANDROID_HOME/ndk/25.2.9519653/build/cmake/android.toolchain.cmake
          
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: ${{ github.workspace }}/whisper-cpp/build/libwhisper.a
          if-no-files-found: error
